--- # Setup a default user - needs to be run as root.
- name: create deploy user
  user:
    name="{{ user }}"
    groups=adm,dialout,cdrom,floppy,audio,dip,video,plugdev,netdev,sudo
    append=yes
    state=present
    shell=/bin/bash

- name: add custom sudoer file
  template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/{{ user }}"
    mode: 0440

- name: Set up multiple authorized keys
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ item }}"
  with_file:
    - "{{ lookup('env', 'PWD') }}/files/keys/marco.pub"
    - "{{ lookup('env', 'PWD') }}/files/keys/rafael.pub"
